version: '3.5'

services:
  web-api-gateway-tests:
    image: web-api-gateway-tests
    build: .
    volumes:
      - .:/usr/src/app:rw
      - ../node_modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: development
      COMUNICATION_LAYER: amqp://localhost
    ports:
      - 4000:4000
      - 9200:9200
    networks: 
      - app_network

  inventario:
    image: inventario
    build: ../services/inventario
    volumes:
      - ../services/inventario:/usr/src/app:rw
      - ../services/inventario/node_modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: development
      COMUNICATION_LAYER: amqp://localhost
    ports:
      - 4001:4001
      - 9201:9201
    networks: 
      - app_network

networks: 
  app_network:
    driver: bridge
    name: app_network